### ISSUE TITLE
Implementing google calendar & maps API

### ISSUE THREAD

**Issue by KevinDeBoeck** [KevinDeBoeck/Internetapplicaties-Site#8]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
New implementation

**Describe alternatives you've considered**
None

**Additional context**
- Volunteer calendar (time slots)
- Diver calendar (time slots)
- Adding map to about page

**Comment by Iloller** [comment]
Didn't use api but maps iframe
